spring:
#  datasource:
#    url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=bz_uf_assist_system
#    username: sa
#    password: sasa
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#  redis:
#    host: 127.0.0.1
#    port: 6379

  # sa-token配置
#  sa-token:
#    # token名称 (同时也是cookie名称)
#    token-name: token
#    # token有效期，单位s 默认30天, -1代表永不过期
#    timeout: 7200
#    # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
#    activity-timeout: 7200
#    # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
#    allow-concurrent-login: false
#    # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
#    is-share: false
#    # token风格
#    token-style: uuid

server:
  port: 8080

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

knife4j:
  enable: true

#公众号配置(可支持多公众号配置，即list表示)
wx:
  mp:
    apps:
      - appId:
        secret:
        token: ebiz
        aesKey:
#    storage:
#      useRedis: true
#      keyPrefix: wxmp
    http:
      clientType: HttpClient
#      proxyHost:
#      proxyPort:
#      proxyUsername:
#      proxyPassword:


